stages:
  - deploy

deploy:
  stage: deploy
  image: php:8.2-cli
  variables:
    FTP_SERVER: "ftp.thesyndicates.team"
    FTP_USERNAME: "thesyndicates@jeromecmb.thesyndicates.team"
    FTP_PASSWORD: "S,hs1Hnklz&7nm-]"
    FTP_PATH: "/" 
  before_script:
    - apt-get update && apt-get install -y lftp unzip git
  script:
    - |
      lftp -u "$FTP_USERNAME","$FTP_PASSWORD" $FTP_SERVER <<EOF
      set ftp:ssl-allow no
      mirror -R --verbose --only-newer --exclude-glob vendor --exclude-glob .env ./ $FTP_PATH
      quit
      EOF
  only:
    - dev