#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

// Define the start time of the application for performance measurement...
define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

//  Bootstrap Laravel and handle the command...
//  @var Application $app
$app = require_once __DIR__ . '/bootstrap/app.php';

// Run the Artisan application and exit with the appropriate code...
$status = $app->handleCommand(new ArgvInput);

// Ensure that any final output is sent before exiting...
exit($status);
